sudo: required 
services:
   - docker

before_install:
   - docker build -t chandrudocrepo/docker-react -f dockerfile.dev .


script:
   - docker run chandrudocrepo/docker-react npm run test -- --coverage 